// ═══════════════════════════════════════════════════════════
// Learning Craft — Standard Autocomplete Suggestion Dictionaries
// ═══════════════════════════════════════════════════════════

import type { AutocompleteSuggestion } from "./types";

// ─── JavaScript & TypeScript Suggestions ───
export const JS_TS_SUGGESTIONS: AutocompleteSuggestion[] = [
  // ─── Keywords ───
  {
    label: "const",
    insertText: "const ",
    kind: "keyword",
    detail: "const statement",
    documentation: "Declares a block-scoped, read-only named constant variable.",
    boost: 95,
  },
  {
    label: "let",
    insertText: "let ",
    kind: "keyword",
    detail: "let statement",
    documentation: "Declares a block-scoped, re-assignable local variable.",
    boost: 95,
  },
  {
    label: "var",
    insertText: "var ",
    kind: "keyword",
    detail: "var statement",
    documentation: "Declares a function-scoped or globally-scoped variable.",
    boost: 70,
  },
  {
    label: "function",
    insertText: "function name() {\n  \n}",
    cursorOffset: 9, // cursor at "name"
    kind: "keyword",
    detail: "function declaration",
    documentation: "Defines a function with the specified parameters and body.",
    boost: 90,
  },
  {
    label: "async",
    insertText: "async ",
    kind: "keyword",
    detail: "async modifier",
    documentation: "Defines an asynchronous function that returns a Promise.",
    boost: 85,
  },
  {
    label: "await",
    insertText: "await ",
    kind: "keyword",
    detail: "await expression",
    documentation: "Pauses execution of an async function until a Promise settles.",
    boost: 85,
  },
  {
    label: "return",
    insertText: "return ",
    kind: "keyword",
    detail: "return statement",
    documentation: "Ends function execution and specifies a value to return.",
    boost: 90,
  },
  {
    label: "if",
    insertText: "if (condition) {\n  \n}",
    cursorOffset: 4, // highlight "condition"
    kind: "keyword",
    detail: "if statement",
    documentation: "Executes a block of code if a specified condition evaluates to truthy.",
    boost: 90,
  },
  {
    label: "else",
    insertText: "else {\n  \n}",
    cursorOffset: 9,
    kind: "keyword",
    detail: "else statement",
    documentation: "Executes code if the preceding if condition was falsy.",
    boost: 80,
  },
  {
    label: "else if",
    insertText: "else if (condition) {\n  \n}",
    cursorOffset: 9,
    kind: "keyword",
    detail: "else if statement",
    documentation: "Specifies a new condition if the previous condition was falsy.",
    boost: 80,
  },
  {
    label: "for",
    insertText: "for (let i = 0; i < array.length; i++) {\n  \n}",
    cursorOffset: 20, // at "array"
    kind: "keyword",
    detail: "for loop",
    documentation: "Creates a loop with three optional expressions enclosed in parentheses.",
    boost: 90,
  },
  {
    label: "for...of",
    insertText: "for (const item of items) {\n  \n}",
    cursorOffset: 19, // at "items"
    kind: "keyword",
    detail: "for..of loop",
    documentation: "Iterates over iterable objects (arrays, strings, sets, maps).",
    boost: 88,
  },
  {
    label: "for...in",
    insertText: "for (const key in object) {\n  \n}",
    cursorOffset: 18, // at "object"
    kind: "keyword",
    detail: "for..in loop",
    documentation: "Iterates over the enumerable properties of an object.",
    boost: 75,
  },
  {
    label: "while",
    insertText: "while (condition) {\n  \n}",
    cursorOffset: 7,
    kind: "keyword",
    detail: "while loop",
    documentation: "Creates a loop that executes as long as a test condition evaluates to true.",
    boost: 80,
  },
  {
    label: "do...while",
    insertText: "do {\n  \n} while (condition);",
    cursorOffset: 7,
    kind: "keyword",
    detail: "do-while statement",
    documentation: "Executes a block of code at least once before testing the condition.",
    boost: 65,
  },
  {
    label: "switch",
    insertText: "switch (key) {\n  case value:\n    break;\n  default:\n    break;\n}",
    cursorOffset: 8,
    kind: "keyword",
    detail: "switch statement",
    documentation: "Evaluates an expression, matching against multiple case clauses.",
    boost: 75,
  },
  {
    label: "case",
    insertText: "case value:\n  break;",
    cursorOffset: 5,
    kind: "keyword",
    detail: "case clause",
    documentation: "Labels a block of code within a switch statement.",
    boost: 70,
  },
  {
    label: "break",
    insertText: "break;",
    kind: "keyword",
    detail: "break statement",
    documentation: "Terminates the current loop, switch, or label statement.",
    boost: 70,
  },
  {
    label: "continue",
    insertText: "continue;",
    kind: "keyword",
    detail: "continue statement",
    documentation: "Terminates execution of the statements in the current iteration of the current loop.",
    boost: 70,
  },
  {
    label: "try...catch",
    insertText: "try {\n  \n} catch (error) {\n  console.error(error);\n}",
    cursorOffset: 8,
    kind: "keyword",
    detail: "try-catch block",
    documentation: "Marks a block of statements to try and handles exceptions that occur.",
    boost: 85,
  },
  {
    label: "throw",
    insertText: "throw new Error(message);",
    cursorOffset: 16,
    kind: "keyword",
    detail: "throw statement",
    documentation: "Throws a user-defined exception.",
    boost: 80,
  },
  {
    label: "new",
    insertText: "new ",
    kind: "keyword",
    detail: "new operator",
    documentation: "Creates an instance of a user-defined object type or built-in object.",
    boost: 85,
  },
  {
    label: "class",
    insertText: "class ClassName {\n  constructor() {\n    \n  }\n}",
    cursorOffset: 6,
    kind: "keyword",
    detail: "class declaration",
    documentation: "Defines a blueprint for creating objects with state and behavior.",
    boost: 85,
  },
  {
    label: "interface",
    insertText: "interface InterfaceName {\n  \n}",
    cursorOffset: 10,
    kind: "interface",
    detail: "TypeScript interface",
    documentation: "Defines a TypeScript contract that an object must adhere to.",
    boost: 85,
  },
  {
    label: "type",
    insertText: "type TypeName = {\n  \n};",
    cursorOffset: 5,
    kind: "type",
    detail: "TypeScript type alias",
    documentation: "Creates a new name for a type or combination of types.",
    boost: 85,
  },
  {
    label: "enum",
    insertText: "enum EnumName {\n  \n}",
    cursorOffset: 5,
    kind: "keyword",
    detail: "TypeScript enum",
    documentation: "Defines a set of named constants.",
    boost: 75,
  },
  {
    label: "import",
    insertText: "import {  } from '';",
    cursorOffset: 9,
    kind: "keyword",
    detail: "import statement",
    documentation: "Imports bindings exported by another module.",
    boost: 80,
  },
  {
    label: "export",
    insertText: "export ",
    kind: "keyword",
    detail: "export statement",
    documentation: "Used when creating JavaScript modules to export live bindings.",
    boost: 80,
  },
  {
    label: "typeof",
    insertText: "typeof ",
    kind: "keyword",
    detail: "typeof operator",
    documentation: "Returns a string indicating the type of the unevaluated operand.",
    boost: 80,
  },
  {
    label: "instanceof",
    insertText: "instanceof ",
    kind: "keyword",
    detail: "instanceof operator",
    documentation: "Tests whether an object has in its prototype chain the constructor prototype.",
    boost: 75,
  },
  {
    label: "null",
    insertText: "null",
    kind: "constant",
    detail: "null literal",
    documentation: "Represents the intentional absence of any object value.",
    boost: 80,
  },
  {
    label: "undefined",
    insertText: "undefined",
    kind: "constant",
    detail: "undefined literal",
    documentation: "Primitive value automatically assigned to variables that have just been declared.",
    boost: 80,
  },
  {
    label: "true",
    insertText: "true",
    kind: "constant",
    detail: "boolean true",
    documentation: "Boolean truth value.",
    boost: 80,
  },
  {
    label: "false",
    insertText: "false",
    kind: "constant",
    detail: "boolean false",
    documentation: "Boolean falsity value.",
    boost: 80,
  },

  // ─── Console APIs ───
  {
    label: "console.log()",
    insertText: "console.log()",
    cursorOffset: 12,
    kind: "function",
    detail: "console.log(message?: any, ...optionalParams: any[]): void",
    documentation: "Outputs a message or object to the playground console.",
    boost: 100,
  },
  {
    label: "console.error()",
    insertText: "console.error()",
    cursorOffset: 14,
    kind: "function",
    detail: "console.error(message?: any, ...optionalParams: any[]): void",
    documentation: "Outputs an error message to the playground console.",
    boost: 92,
  },
  {
    label: "console.warn()",
    insertText: "console.warn()",
    cursorOffset: 13,
    kind: "function",
    detail: "console.warn(message?: any, ...optionalParams: any[]): void",
    documentation: "Outputs a warning message to the playground console.",
    boost: 90,
  },
  {
    label: "console.table()",
    insertText: "console.table()",
    cursorOffset: 14,
    kind: "function",
    detail: "console.table(tabularData?: any, properties?: string[]): void",
    documentation: "Displays tabular data as a table in the console.",
    boost: 88,
  },
  {
    label: "console.info()",
    insertText: "console.info()",
    cursorOffset: 13,
    kind: "function",
    detail: "console.info(message?: any, ...optionalParams: any[]): void",
    documentation: "Outputs an informational message to the console.",
    boost: 85,
  },
  {
    label: "console.clear()",
    insertText: "console.clear()",
    cursorOffset: 15,
    kind: "function",
    detail: "console.clear(): void",
    documentation: "Clears the console log history.",
    boost: 80,
  },
  {
    label: "console.time()",
    insertText: "console.time('timer')",
    cursorOffset: 14,
    kind: "function",
    detail: "console.time(label?: string): void",
    documentation: "Starts a timer you can use to track how long an operation takes.",
    boost: 75,
  },
  {
    label: "console.timeEnd()",
    insertText: "console.timeEnd('timer')",
    cursorOffset: 17,
    kind: "function",
    detail: "console.timeEnd(label?: string): void",
    documentation: "Stops a timer that was previously started by calling console.time().",
    boost: 75,
  },

  // ─── Standard Functions & Utilities ───
  {
    label: "setTimeout()",
    insertText: "setTimeout(() => {\n  \n}, 1000);",
    cursorOffset: 20,
    kind: "function",
    detail: "setTimeout(handler: TimerHandler, timeout?: number): number",
    documentation: "Executes a function or specified piece of code once after the timer expires.",
    boost: 90,
  },
  {
    label: "setInterval()",
    insertText: "setInterval(() => {\n  \n}, 1000);",
    cursorOffset: 21,
    kind: "function",
    detail: "setInterval(handler: TimerHandler, timeout?: number): number",
    documentation: "Repeatedly calls a function or executes a code snippet with a fixed time delay.",
    boost: 85,
  },
  {
    label: "clearTimeout()",
    insertText: "clearTimeout(timerId)",
    cursorOffset: 13,
    kind: "function",
    detail: "clearTimeout(id: number | undefined): void",
    documentation: "Cancels a timeout previously established by calling setTimeout().",
    boost: 80,
  },
  {
    label: "clearInterval()",
    insertText: "clearInterval(intervalId)",
    cursorOffset: 14,
    kind: "function",
    detail: "clearInterval(id: number | undefined): void",
    documentation: "Cancels a timed, repeating action which was previously established by setInterval().",
    boost: 80,
  },
  {
    label: "fetch()",
    insertText: "fetch('url')\n  .then(res => res.json())\n  .then(data => console.log(data));",
    cursorOffset: 7,
    kind: "function",
    detail: "fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response>",
    documentation: "Starts the process of fetching a resource from the network, returning a Promise.",
    boost: 92,
  },
  {
    label: "parseInt()",
    insertText: "parseInt(string, 10)",
    cursorOffset: 9,
    kind: "function",
    detail: "parseInt(string: string, radix?: number): number",
    documentation: "Parses a string argument and returns an integer of the specified radix.",
    boost: 88,
  },
  {
    label: "parseFloat()",
    insertText: "parseFloat(string)",
    cursorOffset: 11,
    kind: "function",
    detail: "parseFloat(string: string): number",
    documentation: "Parses an argument and returns a floating point number.",
    boost: 85,
  },
  {
    label: "isNaN()",
    insertText: "isNaN(value)",
    cursorOffset: 6,
    kind: "function",
    detail: "isNaN(number: number): boolean",
    documentation: "Determines whether a value is NaN when converted to a number.",
    boost: 80,
  },
  {
    label: "structuredClone()",
    insertText: "structuredClone(value)",
    cursorOffset: 16,
    kind: "function",
    detail: "structuredClone<T>(value: T): T",
    documentation: "Creates a deep clone of a given value using the structured clone algorithm.",
    boost: 82,
  },

  // ─── Math Object ───
  {
    label: "Math.floor()",
    insertText: "Math.floor()",
    cursorOffset: 11,
    kind: "function",
    detail: "Math.floor(x: number): number",
    documentation: "Returns the largest integer less than or equal to a given number.",
    boost: 88,
  },
  {
    label: "Math.ceil()",
    insertText: "Math.ceil()",
    cursorOffset: 10,
    kind: "function",
    detail: "Math.ceil(x: number): number",
    documentation: "Always rounds up and returns the smallest integer greater than or equal to a number.",
    boost: 85,
  },
  {
    label: "Math.round()",
    insertText: "Math.round()",
    cursorOffset: 11,
    kind: "function",
    detail: "Math.round(x: number): number",
    documentation: "Returns the value of a number rounded to the nearest integer.",
    boost: 88,
  },
  {
    label: "Math.max()",
    insertText: "Math.max()",
    cursorOffset: 9,
    kind: "function",
    detail: "Math.max(...values: number[]): number",
    documentation: "Returns the largest of the zero or more numbers given as input parameters.",
    boost: 88,
  },
  {
    label: "Math.min()",
    insertText: "Math.min()",
    cursorOffset: 9,
    kind: "function",
    detail: "Math.min(...values: number[]): number",
    documentation: "Returns the smallest of the zero or more numbers given as input parameters.",
    boost: 88,
  },
  {
    label: "Math.random()",
    insertText: "Math.random()",
    cursorOffset: 13,
    kind: "function",
    detail: "Math.random(): number",
    documentation: "Returns a pseudo-random number between 0 (inclusive) and 1 (exclusive).",
    boost: 90,
  },
  {
    label: "Math.abs()",
    insertText: "Math.abs()",
    cursorOffset: 9,
    kind: "function",
    detail: "Math.abs(x: number): number",
    documentation: "Returns the absolute value of a number.",
    boost: 82,
  },
  {
    label: "Math.sqrt()",
    insertText: "Math.sqrt()",
    cursorOffset: 10,
    kind: "function",
    detail: "Math.sqrt(x: number): number",
    documentation: "Returns the square root of a number.",
    boost: 80,
  },

  // ─── JSON Object ───
  {
    label: "JSON.stringify()",
    insertText: "JSON.stringify(value, null, 2)",
    cursorOffset: 15,
    kind: "function",
    detail: "JSON.stringify(value: any, replacer?: any, space?: string | number): string",
    documentation: "Converts a JavaScript value to a JSON formatted string.",
    boost: 92,
  },
  {
    label: "JSON.parse()",
    insertText: "JSON.parse()",
    cursorOffset: 11,
    kind: "function",
    detail: "JSON.parse(text: string, reviver?: any): any",
    documentation: "Parses a JSON string, constructing the JavaScript value described by the string.",
    boost: 92,
  },

  // ─── Object Static Methods ───
  {
    label: "Object.keys()",
    insertText: "Object.keys()",
    cursorOffset: 12,
    kind: "function",
    detail: "Object.keys(o: object): string[]",
    documentation: "Returns an array of a given object's own enumerable property names.",
    boost: 90,
  },
  {
    label: "Object.values()",
    insertText: "Object.values()",
    cursorOffset: 14,
    kind: "function",
    detail: "Object.values<T>(o: { [s: string]: T }): T[]",
    documentation: "Returns an array of a given object's own enumerable string-keyed property values.",
    boost: 90,
  },
  {
    label: "Object.entries()",
    insertText: "Object.entries()",
    cursorOffset: 15,
    kind: "function",
    detail: "Object.entries<T>(o: { [s: string]: T }): [string, T][]",
    documentation: "Returns an array of a given object's own enumerable string-keyed key-value pairs.",
    boost: 90,
  },
  {
    label: "Object.assign()",
    insertText: "Object.assign({}, target)",
    cursorOffset: 18,
    kind: "function",
    detail: "Object.assign<T, U>(target: T, source: U): T & U",
    documentation: "Copies all enumerable own properties from one or more source objects to a target object.",
    boost: 85,
  },
  {
    label: "Object.fromEntries()",
    insertText: "Object.fromEntries(entries)",
    cursorOffset: 19,
    kind: "function",
    detail: "Object.fromEntries<T = any>(entries: Iterable<readonly [PropertyKey, T]>): { [k: string]: T }",
    documentation: "Transforms a list of key-value pairs into an object.",
    boost: 82,
  },
  {
    label: "Object.freeze()",
    insertText: "Object.freeze(obj)",
    cursorOffset: 14,
    kind: "function",
    detail: "Object.freeze<T>(a: T): Readonly<T>",
    documentation: "Freezes an object: other code cannot delete or change its properties.",
    boost: 78,
  },

  // ─── Array Static Methods ───
  {
    label: "Array.isArray()",
    insertText: "Array.isArray()",
    cursorOffset: 14,
    kind: "function",
    detail: "Array.isArray(arg: any): arg is any[]",
    documentation: "Determines whether the passed value is an Array.",
    boost: 90,
  },
  {
    label: "Array.from()",
    insertText: "Array.from()",
    cursorOffset: 11,
    kind: "function",
    detail: "Array.from<T>(arrayLike: ArrayLike<T>): T[]",
    documentation: "Creates a new, shallow-copied Array instance from an iterable or array-like object.",
    boost: 85,
  },

  // ─── Promise Methods ───
  {
    label: "Promise.all()",
    insertText: "Promise.all([])",
    cursorOffset: 13,
    kind: "function",
    detail: "Promise.all<T>(values: Iterable<T | PromiseLike<T>>): Promise<Awaited<T>[]>",
    documentation: "Takes an iterable of promises and returns a single Promise that resolves when all resolve.",
    boost: 90,
  },
  {
    label: "Promise.allSettled()",
    insertText: "Promise.allSettled([])",
    cursorOffset: 20,
    kind: "function",
    detail: "Promise.allSettled<T>(values: Iterable<T | PromiseLike<T>>): Promise<PromiseSettledResult<Awaited<T>>[]>",
    documentation: "Returns a promise that fulfills after all of the given promises have either fulfilled or rejected.",
    boost: 85,
  },
  {
    label: "Promise.resolve()",
    insertText: "Promise.resolve()",
    cursorOffset: 16,
    kind: "function",
    detail: "Promise.resolve<T>(value: T | PromiseLike<T>): Promise<Awaited<T>>",
    documentation: "Returns a Promise object that is resolved with a given value.",
    boost: 85,
  },
  {
    label: "Promise.reject()",
    insertText: "Promise.reject(reason)",
    cursorOffset: 15,
    kind: "function",
    detail: "Promise.reject<T = never>(reason?: any): Promise<T>",
    documentation: "Returns a new Promise object that is rejected with the given reason.",
    boost: 80,
  },

  // ─── Array Methods ───
  {
    label: "map()",
    insertText: "map(item => )",
    cursorOffset: 12,
    kind: "method",
    detail: "(method) Array<T>.map<U>(callbackfn: (value: T, index: number, array: T[]) => U): U[]",
    documentation: "Calls a defined callback function on each element of an array, and returns an array containing the results.",
    boost: 98,
  },
  {
    label: "filter()",
    insertText: "filter(item => )",
    cursorOffset: 15,
    kind: "method",
    detail: "(method) Array<T>.filter(predicate: (value: T, index: number, array: T[]) => boolean): T[]",
    documentation: "Returns the elements of an array that meet the condition specified in a callback function.",
    boost: 98,
  },
  {
    label: "find()",
    insertText: "find(item => )",
    cursorOffset: 13,
    kind: "method",
    detail: "(method) Array<T>.find(predicate: (value: T, index: number, obj: T[]) => boolean): T | undefined",
    documentation: "Returns the value of the first element in the array where predicate is true, and undefined otherwise.",
    boost: 96,
  },
  {
    label: "findIndex()",
    insertText: "findIndex(item => )",
    cursorOffset: 18,
    kind: "method",
    detail: "(method) Array<T>.findIndex(predicate: (value: T, index: number, obj: T[]) => boolean): number",
    documentation: "Returns the index of the first element in the array where predicate is true, and -1 otherwise.",
    boost: 90,
  },
  {
    label: "findLast()",
    insertText: "findLast(item => )",
    cursorOffset: 17,
    kind: "method",
    detail: "(method) Array<T>.findLast(predicate: (value: T, index: number, array: T[]) => boolean): T | undefined",
    documentation: "Iterates the array in reverse order and returns the value of the first element that satisfies the provided testing function.",
    boost: 82,
  },
  {
    label: "reduce()",
    insertText: "reduce((acc, curr) => {\n  return acc;\n}, initialValue)",
    cursorOffset: 26,
    kind: "method",
    detail: "(method) Array<T>.reduce<U>(callbackfn: (previousValue: U, currentValue: T, currentIndex: number) => U, initialValue: U): U",
    documentation: "Calls the specified callback function for all the elements in an array. The return value is the accumulated result.",
    boost: 94,
  },
  {
    label: "forEach()",
    insertText: "forEach(item => {\n  \n})",
    cursorOffset: 20,
    kind: "method",
    detail: "(method) Array<T>.forEach(callbackfn: (value: T, index: number, array: T[]) => void): void",
    documentation: "Performs the specified action for each element in an array.",
    boost: 95,
  },
  {
    label: "some()",
    insertText: "some(item => )",
    cursorOffset: 13,
    kind: "method",
    detail: "(method) Array<T>.some(predicate: (value: T, index: number, array: T[]) => boolean): boolean",
    documentation: "Determines whether the specified callback function returns true for any element of an array.",
    boost: 88,
  },
  {
    label: "every()",
    insertText: "every(item => )",
    cursorOffset: 14,
    kind: "method",
    detail: "(method) Array<T>.every(predicate: (value: T, index: number, array: T[]) => boolean): boolean",
    documentation: "Determines whether all the members of an array satisfy the specified test.",
    boost: 88,
  },
  {
    label: "includes()",
    insertText: "includes(searchElement)",
    cursorOffset: 9,
    kind: "method",
    detail: "(method) Array<T>.includes(searchElement: T, fromIndex?: number): boolean",
    documentation: "Determines whether an array includes a certain element, returning true or false as appropriate.",
    boost: 92,
  },
  {
    label: "indexOf()",
    insertText: "indexOf(searchElement)",
    cursorOffset: 8,
    kind: "method",
    detail: "(method) Array<T>.indexOf(searchElement: T, fromIndex?: number): number",
    documentation: "Returns the index of the first occurrence of a value in an array, or -1 if it is not present.",
    boost: 90,
  },
  {
    label: "slice()",
    insertText: "slice(start, end)",
    cursorOffset: 6,
    kind: "method",
    detail: "(method) Array<T>.slice(start?: number, end?: number): T[]",
    documentation: "Returns a copy of a section of an array.",
    boost: 90,
  },
  {
    label: "splice()",
    insertText: "splice(start, deleteCount)",
    cursorOffset: 7,
    kind: "method",
    detail: "(method) Array<T>.splice(start: number, deleteCount?: number, ...items: T[]): T[]",
    documentation: "Removes elements from an array and, if necessary, inserts new elements in their place.",
    boost: 86,
  },
  {
    label: "push()",
    insertText: "push(item)",
    cursorOffset: 5,
    kind: "method",
    detail: "(method) Array<T>.push(...items: T[]): number",
    documentation: "Appends new elements to the end of an array, and returns the new length of the array.",
    boost: 95,
  },
  {
    label: "pop()",
    insertText: "pop()",
    cursorOffset: 4,
    kind: "method",
    detail: "(method) Array<T>.pop(): T | undefined",
    documentation: "Removes the last element from an array and returns it.",
    boost: 90,
  },
  {
    label: "shift()",
    insertText: "shift()",
    cursorOffset: 6,
    kind: "method",
    detail: "(method) Array<T>.shift(): T | undefined",
    documentation: "Removes the first element from an array and returns it.",
    boost: 85,
  },
  {
    label: "unshift()",
    insertText: "unshift(item)",
    cursorOffset: 8,
    kind: "method",
    detail: "(method) Array<T>.unshift(...items: T[]): number",
    documentation: "Inserts new elements at the start of an array, and returns the new length of the array.",
    boost: 85,
  },
  {
    label: "join()",
    insertText: "join(', ')",
    cursorOffset: 6,
    kind: "method",
    detail: "(method) Array<T>.join(separator?: string): string",
    documentation: "Adds all the elements of an array into a string, separated by the specified separator string.",
    boost: 90,
  },
  {
    label: "sort()",
    insertText: "sort((a, b) => a - b)",
    cursorOffset: 15,
    kind: "method",
    detail: "(method) Array<T>.sort(compareFn?: (a: T, b: T) => number): this",
    documentation: "Sorts an array in place and returns the sorted array.",
    boost: 90,
  },
  {
    label: "reverse()",
    insertText: "reverse()",
    cursorOffset: 8,
    kind: "method",
    detail: "(method) Array<T>.reverse(): T[]",
    documentation: "Reverses the elements in an array in place.",
    boost: 82,
  },
  {
    label: "flat()",
    insertText: "flat(depth)",
    cursorOffset: 5,
    kind: "method",
    detail: "(method) Array<T>.flat<A, D>(this: A, depth?: D): FlatArray<A, D>[]",
    documentation: "Returns a new array with all sub-array elements concatenated into it recursively up to the specified depth.",
    boost: 84,
  },
  {
    label: "flatMap()",
    insertText: "flatMap(item => )",
    cursorOffset: 16,
    kind: "method",
    detail: "(method) Array<T>.flatMap<U>(callback: (value: T, index: number, array: T[]) => U | readonly U[]): U[]",
    documentation: "Calls a defined callback function on each element of an array, then flattens the result into a new array.",
    boost: 84,
  },
  {
    label: "length",
    insertText: "length",
    kind: "property",
    detail: "(property) length: number",
    documentation: "Gets or sets the length of the array or string.",
    boost: 92,
  },

  // ─── String Methods ───
  {
    label: "split()",
    insertText: "split('')",
    cursorOffset: 7,
    kind: "method",
    detail: "(method) String.split(separator: string | RegExp, limit?: number): string[]",
    documentation: "Splits a String object into an array of strings by separating the string into substrings.",
    boost: 94,
  },
  {
    label: "trim()",
    insertText: "trim()",
    cursorOffset: 5,
    kind: "method",
    detail: "(method) String.trim(): string",
    documentation: "Removes whitespace from both ends of this string and returns a new string.",
    boost: 90,
  },
  {
    label: "trimStart()",
    insertText: "trimStart()",
    cursorOffset: 10,
    kind: "method",
    detail: "(method) String.trimStart(): string",
    documentation: "Removes whitespace from the beginning of this string.",
    boost: 80,
  },
  {
    label: "trimEnd()",
    insertText: "trimEnd()",
    cursorOffset: 8,
    kind: "method",
    detail: "(method) String.trimEnd(): string",
    documentation: "Removes whitespace from the end of this string.",
    boost: 80,
  },
  {
    label: "toLowerCase()",
    insertText: "toLowerCase()",
    cursorOffset: 12,
    kind: "method",
    detail: "(method) String.toLowerCase(): string",
    documentation: "Converts all the alphabetic characters in a string to lowercase.",
    boost: 92,
  },
  {
    label: "toUpperCase()",
    insertText: "toUpperCase()",
    cursorOffset: 12,
    kind: "method",
    detail: "(method) String.toUpperCase(): string",
    documentation: "Converts all the alphabetic characters in a string to uppercase.",
    boost: 92,
  },
  {
    label: "startsWith()",
    insertText: "startsWith(searchString)",
    cursorOffset: 11,
    kind: "method",
    detail: "(method) String.startsWith(searchString: string, position?: number): boolean",
    documentation: "Returns true if the sequence of elements begins with searchString, false otherwise.",
    boost: 88,
  },
  {
    label: "endsWith()",
    insertText: "endsWith(searchString)",
    cursorOffset: 9,
    kind: "method",
    detail: "(method) String.endsWith(searchString: string, endPosition?: number): boolean",
    documentation: "Returns true if the sequence of elements ends with searchString, false otherwise.",
    boost: 88,
  },
  {
    label: "replace()",
    insertText: "replace(searchValue, replaceValue)",
    cursorOffset: 8,
    kind: "method",
    detail: "(method) String.replace(searchValue: string | RegExp, replaceValue: string): string",
    documentation: "Replaces text in a string, using a regular expression or search string.",
    boost: 92,
  },
  {
    label: "replaceAll()",
    insertText: "replaceAll(searchValue, replaceValue)",
    cursorOffset: 11,
    kind: "method",
    detail: "(method) String.replaceAll(searchValue: string | RegExp, replaceValue: string): string",
    documentation: "Replace all instances of a substring in a string.",
    boost: 90,
  },
  {
    label: "substring()",
    insertText: "substring(start, end)",
    cursorOffset: 10,
    kind: "method",
    detail: "(method) String.substring(start: number, end?: number): string",
    documentation: "Returns the substring at the specified location within a String object.",
    boost: 85,
  },
  {
    label: "charAt()",
    insertText: "charAt(index)",
    cursorOffset: 7,
    kind: "method",
    detail: "(method) String.charAt(pos: number): string",
    documentation: "Returns the character at the specified index.",
    boost: 82,
  },
  {
    label: "repeat()",
    insertText: "repeat(count)",
    cursorOffset: 7,
    kind: "method",
    detail: "(method) String.repeat(count: number): string",
    documentation: "Returns a String value that is made from count copies of this.",
    boost: 80,
  },

  // ─── Snippets ───
  {
    label: "clg",
    insertText: "console.log()",
    cursorOffset: 12,
    kind: "snippet",
    detail: "console.log snippet",
    documentation: "Quick snippet for console.log()",
    boost: 105,
  },
  {
    label: "arrow",
    insertText: "const fnName = () => {\n  \n};",
    cursorOffset: 6,
    kind: "snippet",
    detail: "() => {} arrow function",
    documentation: "Quick arrow function variable assignment.",
    boost: 96,
  },
  {
    label: "afn",
    insertText: "() => {\n  \n}",
    cursorOffset: 10,
    kind: "snippet",
    detail: "anonymous arrow function",
    documentation: "Quick inline arrow function block.",
    boost: 96,
  },
  {
    label: "trycatch",
    insertText: "try {\n  \n} catch (err) {\n  console.error(err);\n}",
    cursorOffset: 8,
    kind: "snippet",
    detail: "try / catch block",
    documentation: "Error handling block with console.error log.",
    boost: 92,
  },
  {
    label: "promise",
    insertText: "new Promise((resolve, reject) => {\n  \n});",
    cursorOffset: 38,
    kind: "snippet",
    detail: "new Promise snippet",
    documentation: "Instantiates a new Promise with resolve/reject callbacks.",
    boost: 88,
  },
  {
    label: "useState",
    insertText: "const [state, setState] = useState(initialState);",
    cursorOffset: 7,
    kind: "snippet",
    detail: "React useState hook",
    documentation: "Declares a React state variable and updater function.",
    boost: 86,
  },
  {
    label: "useEffect",
    insertText: "useEffect(() => {\n  \n}, []);",
    cursorOffset: 20,
    kind: "snippet",
    detail: "React useEffect hook",
    documentation: "Executes side effects in functional React components.",
    boost: 86,
  },
];

// ─── SQL Suggestions ───
export const SQL_SUGGESTIONS: AutocompleteSuggestion[] = [
  { label: "SELECT", insertText: "SELECT * FROM ", cursorOffset: 14, kind: "keyword", detail: "SQL SELECT statement", boost: 100 },
  { label: "FROM", insertText: "FROM ", kind: "keyword", detail: "SQL FROM clause", boost: 95 },
  { label: "WHERE", insertText: "WHERE ", kind: "keyword", detail: "SQL WHERE clause", boost: 95 },
  { label: "JOIN", insertText: "JOIN ", kind: "keyword", detail: "SQL INNER JOIN", boost: 90 },
  { label: "LEFT JOIN", insertText: "LEFT JOIN ", kind: "keyword", detail: "SQL LEFT OUTER JOIN", boost: 90 },
  { label: "INSERT INTO", insertText: "INSERT INTO table_name (columns) VALUES (values);", cursorOffset: 12, kind: "keyword", detail: "SQL INSERT statement", boost: 88 },
  { label: "UPDATE", insertText: "UPDATE table_name SET column = value WHERE condition;", cursorOffset: 7, kind: "keyword", detail: "SQL UPDATE statement", boost: 88 },
  { label: "DELETE FROM", insertText: "DELETE FROM table_name WHERE condition;", cursorOffset: 12, kind: "keyword", detail: "SQL DELETE statement", boost: 88 },
  { label: "GROUP BY", insertText: "GROUP BY ", kind: "keyword", detail: "SQL GROUP BY clause", boost: 85 },
  { label: "ORDER BY", insertText: "ORDER BY ", kind: "keyword", detail: "SQL ORDER BY clause", boost: 85 },
  { label: "HAVING", insertText: "HAVING ", kind: "keyword", detail: "SQL HAVING clause", boost: 80 },
  { label: "LIMIT", insertText: "LIMIT 10", cursorOffset: 6, kind: "keyword", detail: "SQL LIMIT clause", boost: 85 },
  { label: "COUNT()", insertText: "COUNT(*)", cursorOffset: 6, kind: "function", detail: "SQL Aggregate Function COUNT", boost: 90 },
  { label: "SUM()", insertText: "SUM()", cursorOffset: 4, kind: "function", detail: "SQL Aggregate Function SUM", boost: 85 },
  { label: "AVG()", insertText: "AVG()", cursorOffset: 4, kind: "function", detail: "SQL Aggregate Function AVG", boost: 85 },
  { label: "DISTINCT", insertText: "DISTINCT ", kind: "keyword", detail: "SQL DISTINCT keyword", boost: 80 },
];

// ─── HTML & CSS Suggestions ───
export const HTML_CSS_SUGGESTIONS: AutocompleteSuggestion[] = [
  { label: "div", insertText: "<div className=\"\">\n  \n</div>", cursorOffset: 16, kind: "snippet", detail: "HTML <div> element", boost: 95 },
  { label: "button", insertText: "<button type=\"button\" onClick={}>Click</button>", cursorOffset: 31, kind: "snippet", detail: "HTML <button> element", boost: 92 },
  { label: "input", insertText: "<input type=\"text\" value={} onChange={} />", cursorOffset: 25, kind: "snippet", detail: "HTML <input> element", boost: 90 },
  { label: "span", insertText: "<span></span>", cursorOffset: 6, kind: "snippet", detail: "HTML <span> element", boost: 85 },
  { label: "display", insertText: "display: flex;", kind: "property", detail: "CSS display property", boost: 90 },
  { label: "flex-direction", insertText: "flex-direction: column;", kind: "property", detail: "CSS flex-direction", boost: 85 },
  { label: "align-items", insertText: "align-items: center;", kind: "property", detail: "CSS align-items", boost: 85 },
  { label: "justify-content", insertText: "justify-content: center;", kind: "property", detail: "CSS justify-content", boost: 85 },
];

/**
 * Returns static autocomplete suggestions for a given runtime / language.
 */
export function getSuggestionsForLanguage(language: string): AutocompleteSuggestion[] {
  const lang = (language || "").toLowerCase();
  if (lang.includes("sql") || lang.includes("postgres") || lang.includes("prisma")) {
    return SQL_SUGGESTIONS;
  }
  if (lang.includes("html") || lang.includes("css")) {
    return [...HTML_CSS_SUGGESTIONS, ...JS_TS_SUGGESTIONS];
  }
  // Default: JavaScript / TypeScript / React / NestJS / Node
  return JS_TS_SUGGESTIONS;
}
