"use client";

import { EnhancedCodeBlock } from "@/components/enhanced-code-display";
import { QuickCheck } from "./quick-check";
import {
  SectionContainer,
  TopicHeader,
  WhyBox,
  Divider,
} from "./shared-components";

// ═══════════════════════════════════════════════════════════
// MODULE 8 — SQL QUERY LOGGING & EVENT EMITTERS
// ═══════════════════════════════════════════════════════════

export function QueryLoggingSection() {
  return (
    <SectionContainer number={8} title="SQL Query Logging & Event Subscriptions">
      {/* ── 8.1 Query Logging ── */}
      <div className="mb-16">
        <TopicHeader
          number={1}
          title="Observing Executed SQL Queries in Development"
          description="Configure PrismaClient to print SQL statements, query parameters, and execution latency."
          color="primary"
        />

        <WhyBox>
          <h4 className="font-bold text-sm text-ds-text-strong mb-2 flex items-center gap-2">
            <span>🔍</span> Event-Driven Query Logging
          </h4>
          <p className="text-xs sm:text-sm text-ds-text-sub leading-relaxed mb-3">
            Pass log options in the <code>super()</code> call of <code>PrismaService</code>:
          </p>
          <EnhancedCodeBlock
            code={`// In PrismaService:
constructor() {
  super({
    log: [
      { emit: 'event', level: 'query' }, // Emits event on every query
      { emit: 'stdout', level: 'error' },
      { emit: 'stdout', level: 'warn' },
    ],
  });
}

async onModuleInit() {
  await this.$connect();

  // ⭐ Subscribe to query events to monitor SQL duration:
  // @ts-ignore
  this.$on('query', (e: any) => {
    this.logger.debug(\`Query: \${e.query} - Params: \${e.params} - Duration: \${e.duration}ms\`);
  });
}`}
            language="typescript"
          />
        </WhyBox>

        <QuickCheck
          question="Why is SQL query logging helpful during local feature development?"
          answer="It helps identify slow N+1 query loops and inspect the exact SQL queries generated by Prisma."
        />
      </div>

      <Divider />
    </SectionContainer>
  );
}
